import { Unit } from '../type';
export declare const noop: Function;
export declare const cancelAnimationFrame: ((handle: number) => void) & typeof globalThis.cancelAnimationFrame;
export declare const requestAnimationFrame: ((callback: FrameRequestCallback) => number) & typeof globalThis.requestAnimationFrame;
export declare const vwToPx: (vw: number) => number;
export declare const getX: (width: number) => number;
export declare const getY: (height: number, radius: number, startAngle: number, endAngle: number) => number;
export declare const getWidth: (unit: Unit, width: number) => number;
export declare const getHeight: (unit: string, height: number | undefined, width: number) => number;
export declare const getRadius: (width: number, height: number, lineWidth: number, cos: number) => number;
export declare const getCurrentPercentage: (percentage: number, current: number, speed: number) => number;
export declare const getCurrentAngle: (startAngle: number, endAngle: number, currentPercentage: number) => number;
