export declare const PI: number, round: (x: number) => number, min: (...values: number[]) => number, max: (...values: number[]) => number, abs: (x: number) => number;
export declare const EPCILON = 0.00001;
export declare const equal: (a: number, b: number) => boolean;
export declare const computeCos: (startAngle: number, endAngle: number) => number;
export declare const computeRadius: (width: number, height: number, lineWidth: number, cos: number) => number;
export declare const computeHeight: (height: number, r: number, startAngle: number, endAngle: number) => number;
export declare const computeCurrentPercentage: (percentage: number, current: number, speed: number) => number;
export declare const computeCurrentAngle: (startAngle: number, endAngle: number, currentProcess: number) => number;
export declare const vwToPx: (vw: number) => number;
export declare const noop: Function;
